CXX=gcc
CXXFLAG=-Wall -Wcast-align

INCLUDE=
OBJDIR=./src/
OBJ=$(OBJDIR)*.c
EXECDIR=./lib/
EXECUTABLE=$(EXECDIR)termsnake

TESTINCLUDE=
TESTOBJDIR=./test/
TESTOBJ=$(TESTOBJDIR)tail.c
TESTEXECDIR=./testlib/
TESTEXECUTABLE=$(TESTEXECDIR)tail

all: $(EXECUTABLE)
$(EXECUTABLE): $(OBJ)
	mkdir -p $(EXECDIR)
	$(CXX) $(CXXFLAG) $(INCLUDE) $(OBJ) -o $@

test: $(TESTEXECUTABLE)
$(TESTEXECUTABLE): $(TESTOBJ)
	mkdir -p $(TESTEXECDIR)
	$(CXX) $(CXXFLAG) $(TESTINCLUDE) $(TESTOBJ) -o $@

clean:
	rm -rf $(EXECDIR) $(TESTEXECDIR)
